kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.config.storage.resourceName }}-secret
  labels:
    app: {{ .Values.config.resourceName }}-secret
    group: {{ .Values.config.resourceName }}
    env: {{ .Values.config.env }}
    comp: node
type: Opaque
data:
  azurestorageaccountname: "{{ .Values.config.storage.azureFile.azureStorageAccountName | b64enc }}"
  azurestorageaccountkey: "{{ .Values.config.storage.azureFile.azureStorageAccountKey | b64enc }}"
