kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.storage.resourceName }}
  labels:
    app: {{ .Values.config.resourceName }}-storage
    group: {{ .Values.config.resourceName }}
    env: {{ .Values.config.env }}
provisioner: kubernetes.io/{{ .Values.config.storage.azureFile.provisioner }}
parameters:
  skuName: {{ .Values.config.storage.azureFile.skuName }}
  storageAccount: {{ .Values.config.storage.azureFile.azureStorageAccountName }}
  location: {{ .Values.config.storage.azureFile.location }}
