kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.config.resourceName }}-pvc
  labels:
    app: {{ .Values.config.resourceName }}-pvc
    group: {{ .Values.config.resourceName }}
    env: {{ .Values.config.env }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storage.resourceName }}
  volumeName: {{ .Values.config.resourceName }}-pv-volume
  resources:
    requests:
      storage: {{ .Values.config.storage.node.size }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.config.resourceName }}-pv-volume
  labels:
    app: {{ .Values.config.resourceName }}-pv
    group: {{ .Values.config.resourceName }}
    env: {{ .Values.config.env }}
spec:
  storageClassName: {{ .Values.config.storage.resourceName }}
  capacity:
    storage: {{ .Values.config.storage.node.size }}
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: {{ .Values.config.storage.resourceName }}-secret
    shareName: {{ .Values.config.storage.node.fileShareName }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
